# -*- coding: utf-8 -*-
"""Logic_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvudUb2iwXfvcmSdN-U5wc1Y7NMemgI0

# **Logic 3**
"""

print('==== LOGIC 3 ====')
print()
print()

SIZE = 9



print('Soal 1 - Fibonacci')
print()
f1 = 1
f2 = 1
for i in range(SIZE):
  print(f1, end = ' ')
  fn = f1 + f2
  f1 = f2
  f2 = fn

print()
print()
print()



print('Soal 2 - Fibonacci 3')
print()
f1 = 1
f2 = 1
f3 = 1
for i in range(SIZE):
  print(f1, end = ' ')
  fn = f1 + f2 + f3
  f1 = f2
  f2 = f3
  f3 = fn

print()
print()
print()



print('Soal 3 - FPB & KPK')
print()
a = 120
b = 36
nilai_a = a
nilai_b = b

# FPB
while (b != 0):
  r = a % b
  a, b = b, r

fpb = a
print(f'FPB dari {nilai_a} dan {nilai_b} adalah {fpb}')

# KPK
kpk = (nilai_a * nilai_b) // fpb
print(f'KPK dari {nilai_a} dan {nilai_b} adalah {kpk}')

print()
print()



print('Soal 4')
print()
for row in range(1, SIZE + 1):
    for col in range(1, SIZE + 1):
        if(row == col):
          print((row + col - 1), end = '')
        elif(row + col == SIZE + 1):
          print(((col * 2) - 2), end = '')
        elif(row <= col and row + col <= SIZE + 1):
          print('A', end = '')
        elif(row <= col and row + col >= SIZE + 1):
          print('B', end = '')
        elif(row >= col and row + col >= SIZE + 1):
          print('C', end = '')
        elif(row >= col and row + col <= SIZE + 1):
          print('D', end = '')
        else:
          print(' ', end = '')
    print()
print()
print()



print('Soal 5')
print()
for row in range(1, SIZE + 1):
    for col in range(1, SIZE + 1):
        if (row == 1 or row == SIZE or col == 1 or col == SIZE or row == 2 or row == 8 or col == 2 or col == 8):
            print('1', end = '')
        elif ((row == 3 or row == 7) and 3 <= col <= 7) or ((col == 3 or col == 7) and 3 <= row <= 7):
            print('2', end = '')
        elif ((row == 4 or row == 6) and 4 <= col <= 6) or ((col == 4 or col == 6) and 4 <= row <= 6):
            print('3', end = '')
        elif (row == 5 and col == 5):
            print('5', end = '')
        else:
            print(' ', end = '')
    print()
print()
print()



print('Soal 6')
print()
for row in range(1, SIZE + 1):
    for col in range(1, SIZE + 1):
        if (row == 1 or row == SIZE or col == 1 or col == SIZE):
            print('1', end = '')
        elif ((row == 3 or row == 7) and 3 <= col <= 7) or ((col == 3 or col == 7) and 3 <= row <= 7):
            print('3', end = '')
        elif (row == 5 and col == 5):
            print('5', end = '')
        else:
            print(' ', end = '')
    print()
print()
print()



print('Soal 7')
print()
for row in range(1, SIZE + 1):
    for col in range(1, SIZE + 1):
        if (row == 1 or row == SIZE or col == 1 or col == SIZE) or ((row == 3 or row == 7) and 3 <= col <= 7) or ((col == 3 or col == 7) and 3 <= row <= 7):
            print('1', end = '')
        elif (row == 5 and col == 5):
            print('2', end = '')
        else:
            print(' ', end = '')
    print()
print()
print()



print('Soal 8')
print()
for row in range(1, SIZE + 1):
    for col in range(1, SIZE + 1):
        if (row == 1 or row == SIZE or col == 1 or col == SIZE) or ((row == 3 or row == 7) and 3 <= col <= 7) or((col == 3 or col == 7) and 3 <= row <= 7):
            print('1', end = '')
        elif ((row == 2 or row == 8) and 2 <= col <= 8) or ((col == 2 or col == 8) and 2 <= row <= 8):
            print('A', end = '')
        elif ((row == 4 or row == 6) and 4 <= col <= 6) or ((col == 4 or col == 6) and 4 <= row <= 6):
            print('B', end = '')
        elif row == 5 and col == 5:
            print('2', end = '')
        else:
            print(' ', end = '')
    print()
print()

