# -*- coding: utf-8 -*-
"""Logic_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvudUb2iwXfvcmSdN-U5wc1Y7NMemgI0

# **Logic 5**
"""

print('==== LOGIC 5 ====')
print('\n')


print('Soal 1')
def crange(a, b):
  return range(a, b + 1)
def printnln(a):
  print(a, end = '')
def total(n):
  return n * (n + 1) // 2

for l in crange(1, 4):
  for b in crange(1, l):
    for s in crange(1, total(l) - l):
      printnln(' ')
    for k in crange(1, l):
      printnln('*')
    print()
print('\n\n')



print('Soal 2')
for l in crange(1, 4):
  for b in crange(1, l):
    for s in crange(1, total(4) - total(l)):
      printnln(' ')
    for k in crange(1, l):
      printnln('*')
    print()
print('\n\n')



print('Soal 3')
def totalPyramid(n):
  return n * n
def pyramid(n):
  return n * 2 - 1

for l in crange(1, 3):
  for t in crange(1, l):
    for s in crange(1, totalPyramid(l) - pyramid(l)):
      printnln(' ')
    for sp in crange(1, l - t):
      printnln(' ')
    for kp in crange(1, pyramid(t)):
      printnln('*')
    print()
print('\n\n')



print('Soal 4')
for l in crange(1, 3):
  for t in crange(1, l):
    for s in crange(1, totalPyramid(3) - totalPyramid(l)):
      printnln(' ')
    for sp in crange(1, l - t):
      printnln(' ')
    for kp in crange(1, pyramid(t)):
      printnln('*')
    print()
print('\n\n')



print('Soal 5')
for l in crange(1, 3):
  for t in reversed(crange(1, l)):
    for s in crange(1, totalPyramid(l) - pyramid(l)):
      printnln(' ')
    for sp in crange(1, l - t):
      printnln(' ')
    for kp in crange(1, pyramid(t)):
      printnln('*')
    print()
print('\n\n')



print('Soal 6')
for l in crange(1, 4):
  v = 1
  for b in crange(1, l):
    for s in crange(1, total(l) - l):
      printnln(' ')
    for k in crange(1, l):
      printnln(v)
      v = v + 1
    print()
print('\n\n')



print('Soal 7')
for l in crange(1, 4):
  v = 1
  for b in crange(1, l):
    for s in crange(1, total(4) - total(l)):
      printnln(' ')
    for k in crange(1, l):
      printnln(v)
      v = v + 1
    print()
print('\n\n')



print('Soal 8')
def ganjil(n):
  return n * 2 - 1
def fib(n):
  if n < 2:
     return n
  else:
    return fib(n - 1) + fib(n - 2)


for y in crange(1, 4):
  v = 1
  for t in crange(1, y):
    js = 4 - t
    for s in crange(1, js):
      printnln(' ')
    p = pyramid(t)
    for x in crange(1, p):
      if y == 1:
        printnln(v)
      elif y == 2:
        printnln(v)
      elif y == 3:
        printnln(ganjil(v))
      elif y == 4:
        printnln(fib(v))
      v = v + 1
    print()

