# -*- coding: utf-8 -*-
"""Logic_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycn2Gen4ou4hdQHUwBNy8anFC_DxyPuj

# Belajar Python 3
"""

print('SOAL 1')
UKURAN=9

for x in range(1, UKURAN + 1):
  for y in range(1, UKURAN + 1):
    print((x + y - 1)
    if (x == y)
    else ' ', end='')
  print()

print("SOAL 2")
UKURAN = 9

for x in range(1, UKURAN + 1):
  for y in range(1, UKURAN + 1):
    if(x + y == 10):
      print((y * 2) - 2, end = '')
    else:
      print(' ', end = '')
  print()

print("SOAL 3")
UKURAN= 9
for x in range(1,UKURAN + 1):
  for y in range(1, UKURAN + 1):
    if(x == y):
      print((x + y - 1), end = '')
    elif(x + y == UKURAN + 1):
      print(((y * 2) - 2), end = '')
    else:
      print(' ', end = '')
  print()

print("SOAL 4")
UKURAN = 9  # Ukuran matriks

for x in range(1, UKURAN + 1):  # Loop baris
    for y in range(1, UKURAN + 1):  # Loop kolom
        if x == y:  # Diagonal utama
            print((x + y - 1), end='')
        elif x + y == UKURAN + 1:  # Diagonal sekunder
            print(((y * 2) - 2), end='')
        elif x == 5:  # Baris tengah (x = 5 untuk UKURAN = 9)
            print(((y * 2) - 2), end='')
        elif y == 5:  # Kolom tengah (y = 5 untuk UKURAN = 9)
            print(((x * 2) - 1), end='')
        else:  # Spasi untuk sel kosong
            print(' ', end='')
    print()  # Pindah ke baris berikutnya setelah semua kolom selesai

print("SOAL 5")
UKURAN=9
for x in range(1, UKURAN + 1):
  for y in range(1, UKURAN + 1):
    print(((y * 2) - 1)
    if (x >= y)
    else ' ', end='')
  print()

print("SOAL 6")
UKURAN = 9

for x in range(1, UKURAN + 1):
    for y in range(1, UKURAN + 1):
        print(((UKURAN - x) * 2)
        if (x + y >= UKURAN + 1)
        else ' ', end='')
    print()

print("SOAL 7")
UKURAN=9

for x in range(1, UKURAN + 1):
    for y in range(1, UKURAN + 1):
        if x == y:
            print((x + y - 1), end='')
        elif x + y == UKURAN + 1:
            print(((y * 2) - 2), end='')
        elif x <= y and x + y <= UKURAN + 1:
            print('A', end='')
        elif x >= y and x + y >= UKURAN + 1:
            print('B', end='')
        else:
            print(' ', end='')
    print()

print("SOAL 8")
for x in range(1, UKURAN +1):
  for y in range(1, UKURAN +1):
    if x == y:
      print((x + y -1), end='')
    elif x + y == UKURAN + 1:
      print(((y * 2) -2 ), end='')
    elif x >= y and x + y <= UKURAN + 1:
      print('A', end='')
    elif x <= y and x + y >= UKURAN + 1:
      print('B', end='')
    else:
      print(' ', end='')
  print()

