# -*- coding: utf-8 -*-
"""BelajarPython3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycn2Gen4ou4hdQHUwBNy8anFC_DxyPuj

# Belajar Python 3
"""

print("soal 1")
UKURAN=9
for x in range(1, UKURAN + 1):
  for y in range(1,UKURAN + 1):
    if y == x:
      print("*",end="")
    else:
      print(" ",end="")
  print()

print("soal 2")
UKURAN=9
for y in range(1, UKURAN + 1):  # Loop untuk baris (y)
    for x in range(1, UKURAN + 1):  # Loop untuk kolom (x)
        if x == 9 - (y - 1):  # Kondisi sesuai formula
            print("*", end="")  # Cetak bintang tanpa pindah baris
        else:
            print(" ", end="")  # Cetak spasi tanpa pindah baris
    print()  # Pindah ke baris berikutnya setelah selesai 1 baris

print("soal 3")
UKURAN = 9
for y in range(1, UKURAN + 1):  # Iterasi baris
    for x in range(1, UKURAN + 1):  # Iterasi kolom
        # Kondisi untuk kedua diagonal
        if x == y or x == 10 - y:
            print("*", end="")  # Cetak bintang
        else:
            print(" ", end="")  # Cetak spasi
    print()  # Ganti baris

print("soal 4")
UKURAN = 9
for y in range(1, UKURAN + 1):  # Iterasi untuk baris
    for x in range(1, UKURAN + 1):  # Iterasi untuk kolom
        if x == y:  # Kondisi untuk diagonal kiri atas ke kanan bawah
            print("*", end="")
        elif x == 9 - (y - 1):  # Kondisi untuk diagonal kanan atas ke kiri bawah
            print("*", end="")
        elif x == 5:  # Kondisi untuk kolom ke-5
            print("*", end="")
        elif y == 5:  # Kondisi untuk baris ke-5
            print("*", end="")
        else:
            print(" ", end="")  # Cetak spasi jika tidak ada kondisi yang terpenuhi
    print()  # Pindah ke baris berikutnya setelah selesai satu baris

print("soal 5")
UKURAN = 9
for x in range(1, UKURAN + 1):
  for y in range(1, UKURAN + 1):
    if y <= x:
      print("*", end="")
    else:
      print(" ", end="")
  print()

# karena baris

print("soal 6")
UKURAN = 9
for y in range(1, UKURAN + 1):
  for x in range(1, UKURAN + 1):
    if x >= 9 - (y - 1):
      print("*", end="")
    else:
      print(" ", end="")
  print()

print("soal 7")
UKURAN = 9  # Menentukan ukuran pola (jumlah baris dan kolom)
for y in range(1, UKURAN + 1):  # Iterasi untuk baris (y adalah nomor baris, mulai dari 1 hingga 9)
    for x in range(1, UKURAN + 1):  # Iterasi untuk kolom (x adalah nomor kolom, mulai dari 1 hingga 9)
        if x >= y and x <= 9 - (y - 1):  # Kondisi 1: Cetak bintang di bagian segitiga atas
            print("*", end="")  # Cetak bintang di kolom saat kondisi terpenuhi, tanpa pindah baris
        elif x <= y and x >= 9 - (y - 1):  # Kondisi 2: Cetak bintang di bagian segitiga bawah
            print("*", end="")  # Cetak bintang di kolom saat kondisi terpenuhi, tanpa pindah baris
        else:  # Jika kondisi di atas tidak terpenuhi
            print(" ", end="")  # Cetak spasi, tanpa pindah baris
    print()  # Setelah semua kolom di baris selesai, pindah ke baris berikutnya

print("soal 8")
UKURAN=9
for y in range(1, UKURAN + 1):
   for x in range(1, UKURAN + 1):
      if (x <= y and x + y <= 10) or (x >= y and x + y >= 10):
         print("*", end="")
      else:
         print(" ", end="")
   print()

